### ISSUE TITLE
onnx

### ISSUE THREAD

**Issue by yzk-lab** [lzh420202/FCOSR#1]
作者你好，感谢你的工作，我对无锚的遥感检测也比较感兴趣，想尝试着复现工作。但是遇到了这个问题。我创建了虚拟环境 安装了pytorch、torchvision.编译了 FCOSR和DOTA_devkit. 结果我python train.py  config时 出现了onnx这个属性没有？我是遗漏了什么工作吗？我不能直接在pytorch上实验吗？后面的TensorRT我没用到 是不是这个原因呢？
![T65(GLTNU(~Q`K3EHDLNIXT](https://user-images.githubusercontent.com/41197028/144807853-95e6d15a-2c77-4b6e-80ec-588258ae3feb.png)

**Comment by lzh420202** [comment]
这个是onnx导出会用到的函数，近期会进行更新。我们近期会再次仔细地检查代码，确保在github上地版本是没有问题的，请持续关注。建议你直接给我发邮件，github不长登录。

**Comment by lzh420202** [comment]
问题已经修复了

**Comment by yzk-lab** [comment]
谢谢作者的工作，我先试一试。感谢。
