### ISSUE TITLE
Where is Multi-level sampling strategy (MLS)  in the code?

### ISSUE THREAD

**Issue by youranran** [lzh420202/FCOSR#22]
Hello author, thank you for your work. I want to learn the Multi-level sampling strategy(MLS) part in detail, but I can't find it in the code. Please tell me where MLS is in the code, thanks!

**Comment by lzh420202** [comment]
We write this code in cuda version, you can find it at **mmdet/ops/fcosr_tools/src/tools_kernel.cu**.
