### ISSUE TITLE
HRSC2016 模型下载下来是单个类别的吗

### ISSUE THREAD

**Issue by ccl-private** [lzh420202/FCOSR#23]
如题，我下载了你提供的HRSC2016数据集模型，模型输出1*9，貌似只有一个类别。但data1.5的模型输出有16*9,所以HRSC2016数据集模型只训练了单类别吗？

**Comment by lzh420202** [comment]
HRSC2016数据集通常只用1个类型来表示，这只是习惯问题。DOTA数据集则是全部都用的。

**Comment by ccl-private** [comment]
好的
