### ISSUE TITLE
GDLoss

### ISSUE THREAD

**Issue by zjutlouis1011** [lzh420202/FCOSR#4]
想请教一下，我将fcosr_rx50_32x4d_fpn_3x_dota10_single.py 中的probiouloss 改为GDLoss，在DOTA数据上测试的结果只有68.7，是还有哪里需要修改的地方么？regress_weight=dict(type='iou'))这个需要修改么？

**Comment by lzh420202** [comment]
损失只用target和pred就行了，没有其他的要求。你说的这个GD Loss是新出来的iou类型损失吗？我不知道，能贴个论文地址吗？

**Comment by zjutlouis1011** [comment]
就是你的代码里也有，GDloss，里面包括kld loss和 gwd loss，我用kld loss 跑了一下

**Comment by lzh420202** [comment]
那个是非官方版本的kld损失实现<https://github.com/zhanggefan/rotmmdet>，我还没用过。当时kld论文出来了，但是代码没有开源，我单独把gwd列出来了，不过现在kld开源了，你可以去试试。

**Comment by lzh420202** [comment]
大量测试的结果和GWD，kld论文的说明中印证了一点，这两种方法的收敛速度都比较慢。
其次，像kfiou和probIou这类使用巴氏距离的基础损失会有更好的效果。
