### ISSUE TITLE
论文结果

### ISSUE THREAD

**Issue by bestzsq** [lzh420202/FCOSR#7]
您好,非常好的工作！这里有几个问题想向您请教下。
1. 请问论文中表格4-6的结果是在验证集上测试的呢？还是test结果？代码上的验证过程是基于DOTA1_0_trainval1024.json 和HRSC_L1_train.json的

2. 在做完执行完prepare_dota.py之后,我发现不同类别之间instance数量的差异还是很大的(这里Gaps设置的是200)？不知道这个问题您有没有遇到过？
prepare_dota.py 的setting 如下:
```
Sub patch size: 1024
Gaps: 200
Data type: dota10
Processor number: 16
Multi scale: False
------------------------------
padding: True
```
详细的类别实例个数的统计如下：
[(1, 19647), (2, 1136), (3, 4317), (4, 832), (5, 59578), (6, 43930), (7, 77605), (8, 6093), (9, 1258), (10, 13941), (11, 925), (12, 1002), (13, 16286), (14, 3925), (15, 1260)]

**Comment by lzh420202** [comment]
1、我们采用了一种通用做法，训练数据包括训练集和验证集，测试数据只有测试集。这个在论文里有描述，具体代码中，我们没有在训练过程中进行验证，所以加入了--no-validate选项。至于你提到的那个，其实我是参考其他人的代码写法，具体在执行阶段是不会进行验证的(验证有点问题，我没解决)。
2、开源的代码和我们实际环境中的代码是有一些差异的，主要是自己用的部分没有那么多参数说明。gap默认200是一般的通用切法，但是参考了redet(redet是单尺度200，多尺度500，我们嫌麻烦就统一都用了512，有点强迫症)，DOTA数据集本身就是各种实例分布不均的，有的小目标例如车辆就会很多，桥梁少，这个也没有好的办法。

**Comment by bestzsq** [comment]
对您的工作很感兴趣，也非常感谢您的回复！
关于您回复中有一些疑问的是:
1. 您是在训练的时候加入了--no-validate,比如DOTA数据集的结果是使用DOTA1_0_trainval1024.json训练3x策略,利用analyse_result.py生成的结果提交到DOTA evaluation上得到的结果？HRSC2016的结果则是训练了40k iterations,然后您是通过analyse_result_hrsc.py直接得到HRSC2016结果嘛？

**Comment by lzh420202** [comment]
对的，DOTA的结果都是输出给武大的服务器测的。HRSC是自己测得(HRSC没有服务器来测试)。测试代码我参考了redet的内容(很多东西和redet很像)

**Comment by bestzsq** [comment]
好滴好滴，非常感谢回复
