### ISSUE TITLE
Ellipse center sampling和Fuzzy sample label assignment的区别

### ISSUE THREAD

**Issue by kuazhangxiaoai** [lzh420202/FCOSR#8]
请问，Ellipse center sampling和Fuzzy sample label assignment的区别是什么呢？Ellipse center sampling不就是Fuzzy sample label assignment吗？不都是build target吗？没太看懂。谢谢您的解答。

**Comment by lzh420202** [comment]
椭圆中心采样是确定一个采样范围，一种在长轴方向收缩的椭圆区域；而模糊样本分配是用来解决样本点落在多个目标中的分配策略。
